version: 2.1
jobs:
  test_and_lint:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: /home/circleci/origin-saving-planner
    steps:
      - checkout
      - restore_cache:
          keys:
            - origin-saving-planner-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - origin-saving-planner-deps-develop-{{ checksum "package.json" }}
            - origin-saving-planner-deps-develop
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Linter
          command: |
            npm run lint
      - run:
          name: Run tests
          command: |
            npm run test

workflows:
  version: 2
  pipeline:
    jobs:
      - test_and_lint
